# .github/labeler.yml

# Add 'documentation' label to PRs that modify documentation files
documentation:
  - '*.md' # Includes README.md, CONTRIBUTING.md etc.
  - 'docs/**' # Includes images and docs

# Add 'flutter-app' label to PRs that modify the Flutter application code
flutter-app:
  - 'klubradio_archivum/**'

# Add 'scraper' label to PRs that modify the Node.js scraper
scraper:
  - 'klubradio_scraper_nodejs/**'

# Add 'database' label to PRs that modify database schema or data
database:
  - 'database/**'

# Add 'github-actions' label to PRs that modify workflow files
github-actions:
  - '.github/workflows/**'

# Add 'configuration' label to PRs that modify general configuration files
configuration:
  - '.github/**' # Catch-all for other GitHub config files
  - '.gemini/**'
  - '.idea/**'
  - '*.gitignore'
  - '*.editorconfig'
  - '**/CLAUDE.md'
  - '**/GEMINI.md'

