// Mocks generated by Mockito 5.4.6 from annotations
// in klubradio_archivum/test/api/episode_api_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:klubradio_archivum/services/http_requester.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HttpRequester].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpRequester extends _i1.Mock implements _i2.HttpRequester {
  MockHttpRequester() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, String> get defaultHeaders =>
      (super.noSuchMethod(
            Invocation.getter(#defaultHeaders),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  Duration get connectTimeout =>
      (super.noSuchMethod(
            Invocation.getter(#connectTimeout),
            returnValue: _FakeDuration_0(
              this,
              Invocation.getter(#connectTimeout),
            ),
          )
          as Duration);

  @override
  Duration get requestTimeout =>
      (super.noSuchMethod(
            Invocation.getter(#requestTimeout),
            returnValue: _FakeDuration_0(
              this,
              Invocation.getter(#requestTimeout),
            ),
          )
          as Duration);

  @override
  int get maxRetries =>
      (super.noSuchMethod(Invocation.getter(#maxRetries), returnValue: 0)
          as int);

  @override
  _i3.Future<dynamic> getJson(String? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#getJson, [url], {#headers: headers}),
            returnValue: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);

  @override
  _i3.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
