import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:klubradio_archivum/api/episode_api.dart';
import 'package:klubradio_archivum/services/http_requester.dart';

import 'episode_api_test.mocks.dart'; // This will be generated by build_runner

@GenerateMocks([HttpRequester])
void main() {
  group('EpisodeApi', () {
    late EpisodeApi episodeApi;
    late MockHttpRequester mockHttpRequester;
    const String baseUrl = 'http://localhost:8000';
    const String apiKey = 'test_api_key';

    setUp(() {
      mockHttpRequester = MockHttpRequester();
      episodeApi = EpisodeApi(
        baseUrl: baseUrl,
        apiKey: apiKey,
        requester: mockHttpRequester,
      );
    });

    test('forPodcast returns a list of episodes for a given podcastId',
        () async {
      const podcastId = 'podcast123';
      final List<Map<String, dynamic>> mockResponse = [
        {'id': 'ep1', 'title': 'Episode 1', 'podcastId': podcastId},
        {'id': 'ep2', 'title': 'Episode 2', 'podcastId': podcastId},
      ];

      when(mockHttpRequester.getJson(any)).thenAnswer((_) async => mockResponse);

      final result = await episodeApi.forPodcast(podcastId);

      expect(result, isA<List<Map<String, dynamic>>>());
      expect(result.length, 2);
      expect(result[0]['id'], 'ep1');
      expect(result[1]['podcastId'], podcastId);

      verify(mockHttpRequester.getJson(
              '$baseUrl/rest/v1/episodes?select=*&podcastId=eq.$podcastId&limit=500'))
          .called(1);
    });

    test('recent returns a list of recent episodes', () async {
      final List<Map<String, dynamic>> mockResponse = [
        {'id': 'recent_ep1', 'title': 'Recent Episode 1'},
        {'id': 'recent_ep2', 'title': 'Recent Episode 2'},
      ];

      when(mockHttpRequester.getJson(any)).thenAnswer((_) async => mockResponse);

      final result = await episodeApi.recent(limit: 2);

      expect(result, isA<List<Map<String, dynamic>>>());
      expect(result.length, 2);
      expect(result[0]['id'], 'recent_ep1');

      verify(mockHttpRequester.getJson(
              '$baseUrl/rest/v1/episodes?select=*&order=id.desc&limit=2'))
          .called(1);
    });
  });
}
