// lib/services/static_data_service.dart
import 'dart:convert';
import 'package:flutter/cupertino.dart';
import 'package:flutter/services.dart';

/// Service for loading pre-generated static data bundles that ship with the app.
///
/// These bundles are generated by a GitHub Action and updated daily, providing
/// instant access to commonly accessed data without requiring network calls.
class StaticDataService {
  /// Loads the latest podcasts from the bundled data.
  ///
  /// Returns raw JSON data that can be parsed into Podcast models.
  Future<List<Map<String, dynamic>>> loadLatestPodcasts() async {
    return _loadBundle('assets/data/latest_podcasts.json');
  }

  /// Loads trending podcasts from the bundled data.
  Future<List<Map<String, dynamic>>> loadTrendingPodcasts() async {
    return _loadBundle('assets/data/trending_podcasts.json');
  }

  /// Loads recommended podcasts from the bundled data.
  Future<List<Map<String, dynamic>>> loadRecommendedPodcasts() async {
    return _loadBundle('assets/data/recommended_podcasts.json');
  }

  /// Loads recent episodes from the bundled data.
  Future<List<Map<String, dynamic>>> loadRecentEpisodes() async {
    return _loadBundle('assets/data/recent_episodes.json');
  }

  /// Loads top shows for this year from the bundled data.
  Future<List<Map<String, dynamic>>> loadTopShows() async {
    return _loadBundle('assets/data/top_shows_this_year.json');
  }

  /// Loads complete podcast index for client-side search.
  ///
  /// This is a comprehensive list of all podcasts that can be used for
  /// fast client-side search without network calls.
  Future<List<Map<String, dynamic>>> loadAllPodcastsIndex() async {
    return _loadBundle('assets/data/all_podcasts_index.json');
  }

  /// Internal helper to load and parse a JSON bundle.
  Future<List<Map<String, dynamic>>> _loadBundle(String assetPath) async {
    try {
      final jsonString = await rootBundle.loadString(assetPath);
      final data = jsonDecode(jsonString);

      if (data is List) {
        return data.cast<Map<String, dynamic>>();
      } else if (data is Map<String, dynamic> && data['items'] is List) {
        // Support wrapped format: {"items": [...], "updatedAt": "..."}
        return (data['items'] as List).cast<Map<String, dynamic>>();
      }

      throw FormatException('Unexpected data format in $assetPath');
    } on FlutterError catch (e) {
      // Asset not found or loading failed
      throw StaticDataException(
        'Failed to load static data from $assetPath: ${e.message}',
      );
    } catch (e) {
      throw StaticDataException(
        'Failed to parse static data from $assetPath: $e',
      );
    }
  }

  /// Gets metadata about when the static bundle was last updated.
  ///
  /// Returns null if metadata is not available.
  Future<DateTime?> getBundleUpdateTime() async {
    try {
      final jsonString = await rootBundle.loadString(
        'assets/data/metadata.json',
      );
      final data = jsonDecode(jsonString);

      if (data is Map<String, dynamic> && data['updatedAt'] is String) {
        return DateTime.parse(data['updatedAt']);
      }
    } catch (_) {
      // Metadata file not found or invalid - this is not critical
    }
    return null;
  }
}

/// Exception thrown when static data cannot be loaded or parsed.
class StaticDataException implements Exception {
  StaticDataException(this.message);
  final String message;

  @override
  String toString() => 'StaticDataException: $message';
}
