name: Deploy Web App

on:
  workflow_dispatch:
  push:
    branches:
      - dev # Or your main branch for deployments

defaults:
  run:
    working-directory: klubradio_archivum

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'



      - name: Install dependencies
        run: flutter pub get

      - name: Build Web App
        run: flutter build web --release --base-href /klubradio/

      - name: Upload Web Build Artifact
        uses: actions/upload-artifact@v5
        with:
          name: web-app
          path: klubradio_archivum/build/web
          retention-days: 14
