// Mocks generated by Mockito 5.4.6 from annotations
// in klubradio_archivum/test/providers/episode_provider_queue_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:drift/drift.dart' as _i3;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i5;
import 'package:http/http.dart' as _i14;
import 'package:just_audio/just_audio.dart' as _i8;
import 'package:klubradio_archivum/db/app_database.dart' as _i4;
import 'package:klubradio_archivum/models/episode.dart' as _i9;
import 'package:klubradio_archivum/models/podcast.dart' as _i12;
import 'package:klubradio_archivum/models/show_data.dart' as _i13;
import 'package:klubradio_archivum/models/user_profile.dart' as _i2;
import 'package:klubradio_archivum/services/api_service.dart' as _i10;
import 'package:klubradio_archivum/services/audio_player_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserProfile_0 extends _i1.SmartFake implements _i2.UserProfile {
  _FakeUserProfile_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrationStrategy_1 extends _i1.SmartFake
    implements _i3.MigrationStrategy {
  _FakeMigrationStrategy_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AppDatabaseManager_2 extends _i1.SmartFake
    implements _i4.$AppDatabaseManager {
  _Fake$AppDatabaseManager_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$SubscriptionsTable_3 extends _i1.SmartFake
    implements _i4.$SubscriptionsTable {
  _Fake$SubscriptionsTable_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$EpisodesTable_4 extends _i1.SmartFake
    implements _i4.$EpisodesTable {
  _Fake$EpisodesTable_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$SettingsTable_5 extends _i1.SmartFake
    implements _i4.$SettingsTable {
  _Fake$SettingsTable_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeneratedDatabase_6 extends _i1.SmartFake
    implements _i3.GeneratedDatabase {
  _FakeGeneratedDatabase_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_7 extends _i1.SmartFake
    implements _i3.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryUpdateRules_8 extends _i1.SmartFake
    implements _i3.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_9 extends _i1.SmartFake
    implements _i3.DatabaseConnection {
  _FakeDatabaseConnection_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_10 extends _i1.SmartFake implements _i3.QueryExecutor {
  _FakeQueryExecutor_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_11 extends _i1.SmartFake
    implements _i5.StreamQueryStore {
  _FakeStreamQueryStore_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_12 extends _i1.SmartFake
    implements _i3.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrator_13 extends _i1.SmartFake implements _i3.Migrator {
  _FakeMigrator_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_14<T> extends _i1.SmartFake implements _i6.Future<T> {
  _FakeFuture_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_15<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.InsertStatement<T1, D1> {
  _FakeInsertStatement_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_16<T extends _i3.Table, D> extends _i1.SmartFake
    implements _i3.UpdateStatement<T, D> {
  _FakeUpdateStatement_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_17<T1 extends _i3.HasResultSet, D>
    extends _i1.SmartFake
    implements _i3.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_18<FirstT extends _i3.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i3.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_19<Row> extends _i1.SmartFake
    implements _i3.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_20<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_21<T> extends _i1.SmartFake implements _i3.Selectable<T> {
  _FakeSelectable_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_22 extends _i1.SmartFake
    implements _i3.GenerationContext {
  _FakeGenerationContext_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AudioPlayerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioPlayerService extends _i1.Mock
    implements _i7.AudioPlayerService {
  MockAudioPlayerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<bool> get bufferingStream =>
      (super.noSuchMethod(
            Invocation.getter(#bufferingStream),
            returnValue: _i6.Stream<bool>.empty(),
          )
          as _i6.Stream<bool>);

  @override
  _i6.Stream<Duration> get positionStream =>
      (super.noSuchMethod(
            Invocation.getter(#positionStream),
            returnValue: _i6.Stream<Duration>.empty(),
          )
          as _i6.Stream<Duration>);

  @override
  _i6.Stream<Duration> get bufferedPositionStream =>
      (super.noSuchMethod(
            Invocation.getter(#bufferedPositionStream),
            returnValue: _i6.Stream<Duration>.empty(),
          )
          as _i6.Stream<Duration>);

  @override
  _i6.Stream<_i8.PlayerState> get playerStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#playerStateStream),
            returnValue: _i6.Stream<_i8.PlayerState>.empty(),
          )
          as _i6.Stream<_i8.PlayerState>);

  @override
  bool get isPlaying =>
      (super.noSuchMethod(Invocation.getter(#isPlaying), returnValue: false)
          as bool);

  @override
  _i6.Future<void> loadEpisode(
    _i9.Episode? episode, {
    bool? autoplay = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadEpisode, [episode], {#autoplay: autoplay}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> togglePlayPause() =>
      (super.noSuchMethod(
            Invocation.method(#togglePlayPause, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> seek(Duration? position) =>
      (super.noSuchMethod(
            Invocation.method(#seek, [position]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setSpeed(double? speed) =>
      (super.noSuchMethod(
            Invocation.method(#setSpeed, [speed]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setVolume(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [volume]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i10.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get supabaseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#supabaseUrl),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#supabaseUrl),
            ),
          )
          as String);

  @override
  String get supabaseKey =>
      (super.noSuchMethod(
            Invocation.getter(#supabaseKey),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#supabaseKey),
            ),
          )
          as String);

  @override
  bool get hasValidCredentials =>
      (super.noSuchMethod(
            Invocation.getter(#hasValidCredentials),
            returnValue: false,
          )
          as bool);

  @override
  _i6.Future<List<_i12.Podcast>> fetchLatestPodcasts({int? limit = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchLatestPodcasts, [], {#limit: limit}),
            returnValue: _i6.Future<List<_i12.Podcast>>.value(<_i12.Podcast>[]),
          )
          as _i6.Future<List<_i12.Podcast>>);

  @override
  _i6.Future<List<_i12.Podcast>> fetchTrendingPodcasts({int? limit = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTrendingPodcasts, [], {#limit: limit}),
            returnValue: _i6.Future<List<_i12.Podcast>>.value(<_i12.Podcast>[]),
          )
          as _i6.Future<List<_i12.Podcast>>);

  @override
  _i6.Future<List<_i12.Podcast>> fetchRecommendedPodcasts({int? limit = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRecommendedPodcasts, [], {#limit: limit}),
            returnValue: _i6.Future<List<_i12.Podcast>>.value(<_i12.Podcast>[]),
          )
          as _i6.Future<List<_i12.Podcast>>);

  @override
  _i6.Future<List<_i9.Episode>> fetchEpisodesForPodcast(
    String? podcastId, {
    int? limit = 500,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchEpisodesForPodcast,
              [podcastId],
              {#limit: limit},
            ),
            returnValue: _i6.Future<List<_i9.Episode>>.value(<_i9.Episode>[]),
          )
          as _i6.Future<List<_i9.Episode>>);

  @override
  _i6.Future<List<_i9.Episode>> fetchRecentEpisodes({int? limit = 8}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRecentEpisodes, [], {#limit: limit}),
            returnValue: _i6.Future<List<_i9.Episode>>.value(<_i9.Episode>[]),
          )
          as _i6.Future<List<_i9.Episode>>);

  @override
  _i6.Future<List<_i12.Podcast>> searchPodcasts(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchPodcasts, [query]),
            returnValue: _i6.Future<List<_i12.Podcast>>.value(<_i12.Podcast>[]),
          )
          as _i6.Future<List<_i12.Podcast>>);

  @override
  _i6.Future<List<_i9.Episode>> searchEpisodes(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchEpisodes, [query]),
            returnValue: _i6.Future<List<_i9.Episode>>.value(<_i9.Episode>[]),
          )
          as _i6.Future<List<_i9.Episode>>);

  @override
  _i6.Future<List<_i13.ShowData>> fetchTopShowsThisYear() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTopShowsThisYear, []),
            returnValue: _i6.Future<List<_i13.ShowData>>.value(
              <_i13.ShowData>[],
            ),
          )
          as _i6.Future<List<_i13.ShowData>>);

  @override
  _i6.Future<_i12.Podcast?> fetchPodcastById(String? podcastId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPodcastById, [podcastId]),
            returnValue: _i6.Future<_i12.Podcast?>.value(),
          )
          as _i6.Future<_i12.Podcast?>);

  @override
  _i6.Future<_i2.UserProfile> fetchUserProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserProfile, [userId]),
            returnValue: _i6.Future<_i2.UserProfile>.value(
              _FakeUserProfile_0(
                this,
                Invocation.method(#fetchUserProfile, [userId]),
              ),
            ),
          )
          as _i6.Future<_i2.UserProfile>);

  @override
  _i6.Future<void> logPlayback({required String? episodeId}) =>
      (super.noSuchMethod(
            Invocation.method(#logPlayback, [], {#episodeId: episodeId}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  String getServerErrorMessage(_i14.Response? response) =>
      (super.noSuchMethod(
            Invocation.method(#getServerErrorMessage, [response]),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#getServerErrorMessage, [response]),
            ),
          )
          as String);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i4.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion =>
      (super.noSuchMethod(Invocation.getter(#schemaVersion), returnValue: 0)
          as int);

  @override
  _i3.MigrationStrategy get migration =>
      (super.noSuchMethod(
            Invocation.getter(#migration),
            returnValue: _FakeMigrationStrategy_1(
              this,
              Invocation.getter(#migration),
            ),
          )
          as _i3.MigrationStrategy);

  @override
  _i4.$AppDatabaseManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _Fake$AppDatabaseManager_2(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i4.$AppDatabaseManager);

  @override
  _i4.$SubscriptionsTable get subscriptions =>
      (super.noSuchMethod(
            Invocation.getter(#subscriptions),
            returnValue: _Fake$SubscriptionsTable_3(
              this,
              Invocation.getter(#subscriptions),
            ),
          )
          as _i4.$SubscriptionsTable);

  @override
  _i4.$EpisodesTable get episodes =>
      (super.noSuchMethod(
            Invocation.getter(#episodes),
            returnValue: _Fake$EpisodesTable_4(
              this,
              Invocation.getter(#episodes),
            ),
          )
          as _i4.$EpisodesTable);

  @override
  _i4.$SettingsTable get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _Fake$SettingsTable_5(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i4.$SettingsTable);

  @override
  Iterable<_i3.TableInfo<_i3.Table, Object?>> get allTables =>
      (super.noSuchMethod(
            Invocation.getter(#allTables),
            returnValue: <_i3.TableInfo<_i3.Table, Object?>>[],
          )
          as Iterable<_i3.TableInfo<_i3.Table, Object?>>);

  @override
  List<_i3.DatabaseSchemaEntity> get allSchemaEntities =>
      (super.noSuchMethod(
            Invocation.getter(#allSchemaEntities),
            returnValue: <_i3.DatabaseSchemaEntity>[],
          )
          as List<_i3.DatabaseSchemaEntity>);

  @override
  _i3.GeneratedDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeGeneratedDatabase_6(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i3.GeneratedDatabase);

  @override
  _i3.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_7(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i3.DriftDatabaseOptions);

  @override
  _i3.StreamQueryUpdateRules get streamUpdateRules =>
      (super.noSuchMethod(
            Invocation.getter(#streamUpdateRules),
            returnValue: _FakeStreamQueryUpdateRules_8(
              this,
              Invocation.getter(#streamUpdateRules),
            ),
          )
          as _i3.StreamQueryUpdateRules);

  @override
  _i3.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_9(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i3.DatabaseConnection);

  @override
  _i3.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i11.dummyValue<_i3.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i3.SqlTypes);

  @override
  _i3.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_10(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i3.QueryExecutor);

  @override
  _i5.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_11(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i5.StreamQueryStore);

  @override
  _i3.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_12(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i3.DatabaseConnectionUser);

  @override
  _i6.Future<int> touchEpisode(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#touchEpisode, [id]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> touchSubscription(String? podcastId) =>
      (super.noSuchMethod(
            Invocation.method(#touchSubscription, [podcastId]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i3.Migrator createMigrator() =>
      (super.noSuchMethod(
            Invocation.method(#createMigrator, []),
            returnValue: _FakeMigrator_13(
              this,
              Invocation.method(#createMigrator, []),
            ),
          )
          as _i3.Migrator);

  @override
  _i6.Future<void> beforeOpen(
    _i3.QueryExecutor? executor,
    _i3.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#beforeOpen, [executor, details]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Ret> computeWithDatabase<Ret, DB extends _i3.GeneratedDatabase>({
    required _i6.FutureOr<Ret> Function(DB)? computation,
    required DB Function(_i3.DatabaseConnection)? connect,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#computeWithDatabase, [], {
              #computation: computation,
              #connect: connect,
            }),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<Ret>(
                    this,
                    Invocation.method(#computeWithDatabase, [], {
                      #computation: computation,
                      #connect: connect,
                    }),
                  ),
                  (Ret v) => _i6.Future<Ret>.value(v),
                ) ??
                _FakeFuture_14<Ret>(
                  this,
                  Invocation.method(#computeWithDatabase, [], {
                    #computation: computation,
                    #connect: connect,
                  }),
                ),
          )
          as _i6.Future<Ret>);

  @override
  _i6.Stream<T> createStream<T extends Object>(
    _i5.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i6.Stream<T>.empty(),
          )
          as _i6.Stream<T>);

  @override
  T alias<T, D>(_i3.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i11.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i3.TableInfo<_i3.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i3.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Stream<Set<_i3.TableUpdate>> tableUpdates([
    _i3.TableUpdateQuery? query = const _i3.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i6.Stream<Set<_i3.TableUpdate>>.empty(),
          )
          as _i6.Stream<Set<_i3.TableUpdate>>);

  @override
  _i6.Future<T> doWhenOpened<T>(
    _i6.FutureOr<T> Function(_i3.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_14<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i6.Future<T>);

  @override
  _i3.InsertStatement<T, D> into<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_15<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i3.InsertStatement<T, D>);

  @override
  _i3.UpdateStatement<Tbl, R> update<Tbl extends _i3.Table, R>(
    _i3.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_16<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i3.UpdateStatement<Tbl, R>);

  @override
  _i3.SimpleSelectStatement<T, R> select<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_17<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i3.SimpleSelectStatement<T, R>);

  @override
  _i3.JoinedSelectStatement<T, R> selectOnly<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_18<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i3.JoinedSelectStatement<T, R>);

  @override
  _i3.BaseSelectStatement<_i3.TypedResult> selectExpressions(
    Iterable<_i3.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_19<_i3.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i3.BaseSelectStatement<_i3.TypedResult>);

  @override
  _i3.DeleteStatement<T, D> delete<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_20<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i3.DeleteStatement<T, D>);

  @override
  _i6.Future<int> customUpdate(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> customInsert(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i3.QueryRow>> customWriteReturning(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i6.Future<List<_i3.QueryRow>>.value(<_i3.QueryRow>[]),
          )
          as _i6.Future<List<_i3.QueryRow>>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelect(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_21<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelectQuery(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_21<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i6.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<T> transaction<T>(
    _i6.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_14<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i6.Future<T>);

  @override
  _i6.Future<T> exclusively<T>(_i6.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_14<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i6.Future<T>);

  @override
  _i6.Future<void> batch(_i6.FutureOr<void> Function(_i3.Batch)? runInBatch) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<T> runWithInterceptor<T>(
    _i6.Future<T> Function()? action, {
    required _i3.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_14<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i6.Future<T>);

  @override
  _i3.GenerationContext $write(
    _i3.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_22(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  _i3.GenerationContext $writeInsertable(
    _i3.TableInfo<_i3.Table, dynamic>? table,
    _i3.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_22(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);
}
